<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNvBZxW5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNvBZxW5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNvBZxW5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNvBZxW5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNvBZxW5\App_KernelDevDebugContainer([
    'container.build_hash' => 'NvBZxW5',
    'container.build_id' => '4a5fc207',
    'container.build_time' => 1742990288,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNvBZxW5');
